### ISSUE TITLE
messed up faces and uvs

### ISSUE THREAD

**Issue by vfig** [RSoul82/Blender-NewDark-Toolkit#7]
Many thief 2 models fail to import correctly; vertices are in the correct positions, but random faces seem to be flipped (or missing?) and uvs are extremely wrong.

bushj1 in-game:
![bushj1_game](https://github.com/RSoul82/Blender-NewDark-Toolkit/assets/81129/0e533769-fa7d-420d-a169-1caf12e6f6b0)

bushj1 after import:
![bushj1_frome](https://github.com/RSoul82/Blender-NewDark-Toolkit/assets/81129/4cb24db1-c28e-4d12-bf5d-dfc2a798b37b)

Some models that exhibit this behaviour:
- bushj1.bin
- bushspr1.bin
- mecspot1.bin

(This might be a red herring, but one thing these three models seem to have in common is transparent materials.)

For a long time I thought this was a bintoe bug, not handling some quirks of the .bin format correctly. However, I just discovered today that I get the correct geometry and uvs if I instead pass the .e files through eto3ds, and then import the .3ds file into blender.

bushj1 via 3ds:
![bushj1_from3ds](https://github.com/RSoul82/Blender-NewDark-Toolkit/assets/81129/95be897c-f765-43c0-be7b-8b50fe297eb4)

Since the same .e file is used in both the failed and the correct result, I conclude that the error is not in bintoe after all, but that something is going wrong with the .e loading in this addon.

(I don't want to get distracted from my current fm at the moment, so I am going to use this workaround-via-3ds, and am logging the issue here so I can come back and investigate it later.)

Version info:
- blender 3.0 (for Blender Newdark Toolkit)
- blender 3.6.1 (for 3DS import)
- bintoe 1.42
- eto3ds 1.40

**Comment by RSoul82** [comment]
Code tweaked as per skol's suggestion on Discord.
